CREATE DATABASE QLMETRO;
USE QLMETRO;

CREATE TABLE TAUDIEN
(
	MSTau CHAR(5) NOT NULL,
    TenTau VARCHAR(50) NOT NULL,
    SLToa INT NOT NULL,
    TrangThai VARCHAR(50) NOT NULL,
    GioKH TIME NOT NULL,
    GioKT TIME NOT NULL,
    MSTuyen CHAR(5) NOT NULL,
    CONSTRAINT PRIMARY KEY (MSTau),
    CONSTRAINT FOREIGN KEY (MSTuyen) REFERENCES TUYENDUONG(MSTuyen)
);
CREATE TABLE GATAU
(
	MSGa CHAR(5) NOT NULL,
    TenGa VARCHAR(50) NOT NULL,
    DiaChi VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY KEY (MSGa)
);
CREATE TABLE TUYENDUONG
(
	MSTuyen CHAR(5) NOT NULL,
    TenTuyen VARCHAR(50) NOT NULL,
    ChieuDai FLOAT NOT NULL,
    SLGa INT NOT NULL,
    GaBD CHAR(5) NOT NULL,
    GaKT CHAR(5) NOT NULL,
    CONSTRAINT PRIMARY KEY (MSTuyen),
    CONSTRAINT fk_gabd_td FOREIGN KEY (GaBD) REFERENCES GATAU(MSGa),
    CONSTRAINT fk_gakt_td FOREIGN KEY (GaKT) REFERENCES GATAU(MSGa)
);
CREATE TABLE GADIQUA
(
	MSTuyen CHAR(5) NOT NULL,
    MSGa CHAR(5) NOT NULL,
    ThuTu INT,
    CONSTRAINT pk_mstuyen_msga_gdq PRIMARY KEY (MSTuyen, MSGa),
    CONSTRAINT fk_mstuyen_gdq FOREIGN KEY (MSTuyen) REFERENCES TUYENDUONG(MSTuyen),
    CONSTRAINT fk_msga_gdq FOREIGN KEY (MSGa) REFERENCES GATAU(MSGa)
);
CREATE TABLE VAITRO
(
	MSVT CHAR(5) NOT NULL,
    TenVT VARCHAR(50) NOT NULL,
    CONSTRAINT PRIMARY KEY (MSVT)
);
CREATE TABLE NHANVIEN
(
	MSNV CHAR(5) NOT NULL,
    TenNV VARCHAR(50) NOT NULL,
    GioiTinh VARCHAR(5) NOT NULL,
    DiaChi VARCHAR(50) NOT NULL,
    SoDT VARCHAR(10),
    MSVT CHAR(5) NOT NULL,
    MSDoi CHAR(5),
    CONSTRAINT PRIMARY KEY (MSNV),
    CONSTRAINT fk_msvt_nv FOREIGN KEY (MSVT) REFERENCES VAITRO(MSVT),
    CONSTRAINT fk_msdoi_nv FOREIGN KEY (MSDoi) REFERENCES DOIBAOTRI(MSDoi)
);					
CREATE TABLE NV_TAUDIEN
(
	MSTau CHAR(5) NOT NULL,
    MSNV CHAR(5) NOT NULL,
    CONSTRAINT pk_mstau_msnv_nvtd PRIMARY KEY (MSTau, MSNV),
    CONSTRAINT fk_mstau_nvtd FOREIGN KEY (MSTau) REFERENCES TAUDIEN(MSTau),
    CONSTRAINT fk_msnv_nvtd FOREIGN KEY (MSNV) REFERENCES NHANVIEN(MSNV)
);
CREATE TABLE NV_GATAU
(
	MSGa CHAR(5) NOT NULL,
    MSNV CHAR(5) NOT NULL,
    CONSTRAINT pk_msga_msnv_nvgt PRIMARY KEY (MSGa, MSNV),
    CONSTRAINT fk_msga_nvgt FOREIGN KEY (MSGa) REFERENCES GATAU(MSGa),
    CONSTRAINT fk_msnv_nvgt FOREIGN KEY (MSNV) REFERENCES NHANVIEN(MSNV)
);
CREATE TABLE HANHKHACH
(
	MSHK CHAR(5) NOT NULL,
    TenHK VARCHAR(50),
    GioiTinh VARCHAR(5),
    CCCD CHAR(12),
    SoDT VARCHAR(10),
    CONSTRAINT PRIMARY KEY (MSHK)
);				
CREATE TABLE LOAIVE
(
	MSLoai CHAR(5) NOT NULL,
    TenLoai VARCHAR(50) NOT NULL,
    GiaVe DECIMAL(9,0),
    CONSTRAINT PRIMARY KEY (MSLoai)
);
CREATE TABLE CHUYENDI
(
	MSChuyen CHAR(5) NOT NULL,
    GaDi CHAR(5) NOT NULL,
    GaDen CHAR(5) NOT NULL,
    TGDiDuKien TIME NOT NULL,
    TGDenDuKien TIME NOT NULL,
    MSTuyen CHAR(5) NOT NULL,
    GiaVeLuot DECIMAL(9,0),
    CONSTRAINT PRIMARY KEY (MSChuyen),
    CONSTRAINT fk_gadi_cd FOREIGN KEY (GaDi) REFERENCES GATAU(MSGa),
    CONSTRAINT fk_gaden_cd FOREIGN KEY (GaDen) REFERENCES GATAU(MSGa),
    CONSTRAINT fk_mstuyen_cd FOREIGN KEY (MSTuyen) REFERENCES TUYENDUONG(MSTuyen)
);
CREATE TABLE VETAU
(
	MSVe CHAR(5) NOT NULL,
    MSHK CHAR(5) NOT NULL,
    MSChuyen CHAR(5) NOT NULL,
    MSLoai CHAR(5) NOT NULL,
    TGMua DATETIME NOT NULL,
    TGHieuLuc DATETIME NOT NULL,
    TrangThai VARCHAR(50),
    PhuongThuc VARCHAR(50),
    CONSTRAINT PRIMARY KEY (MSVe),
    CONSTRAINT fk_mshk_vt FOREIGN KEY (MSHK) REFERENCES HANHKHACH(MSHK),
    CONSTRAINT fk_mschuyen_vt FOREIGN KEY (MSChuyen) REFERENCES CHUYENDI(MSChuyen),
    CONSTRAINT fk_msloai_vt FOREIGN KEY (MSLoai) REFERENCES LOAIVE(MSLoai)
);
CREATE TABLE DOIBAOTRI
(
	MSDoi CHAR(5) NOT NULL,
    TenDoi VARCHAR(50) NOT NULL,
    SLThanhVien INT,
    CONSTRAINT PRIMARY KEY (MSDoi)
);
CREATE TABLE BT_TAU
(
	MSDoi CHAR(5) NOT NULL,
    MSTau CHAR(5) NOT NULL,
    NgayBD DATE,
    TrangThai VARCHAR(50),
    CONSTRAINT ok_msdoi_mstau_bttau PRIMARY KEY (MSDoi, MSTau),
    CONSTRAINT fk_msdoi_bttau FOREIGN KEY (MSDoi) REFERENCES DOIBAOTRI(MSDoi),
    CONSTRAINT fk_mstau_bttau FOREIGN KEY (MSTau) REFERENCES TAUDIEN(MSTau)
);
CREATE TABLE BT_TUYEN
(
	MSDoi CHAR(5) NOT NULL,
    MSTuyen CHAR(5) NOT NULL,
    NgayBD DATE,
    TrangThai VARCHAR(50),
    CONSTRAINT pk_msdoi_mstuyen_bttuyen PRIMARY KEY (MSDoi, MSTuyen),
    CONSTRAINT fk_msdoi_bttuyen FOREIGN KEY (MSDoi) REFERENCES DOIBAOTRI(MSDoi),
    CONSTRAINT fk_mstuyen_bttuyen FOREIGN KEY (MSTuyen) REFERENCES TUYENDUONG(MSTuyen)
);
CREATE TABLE BT_GA
(
	MSDoi CHAR(5) NOT NULL,
    MSGa CHAR(5) NOT NULL,
    NgayBD DATE,
    TrangThai VARCHAR(50),
    CONSTRAINT pk_msdoi_msga_btg PRIMARY KEY (MSDoi, MSGa),
    CONSTRAINT fk_msdoi_btg FOREIGN KEY (MSDoi) REFERENCES DOIBAOTRI(MSDoi),
    CONSTRAINT fk_msga_btg FOREIGN KEY (MSGa) REFERENCES GATAU(MSGa)
);
CREATE TABLE THOITIET
(
	MSDB CHAR(5) NOT NULL,
    TrangThai VARCHAR(50) NOT NULL,
    TGCapNhat DATETIME NOT NULL,
    CONSTRAINT PRIMARY KEY (MSDB)
);
CREATE TABLE DB_TUYEN
(
	MSDB CHAR(5),
    MSTuyen CHAR(5),
    TGAnhHuong DATE,
    TTAnhHuong VARCHAR(50),
    CONSTRAINT pk_mstuyen_msdb_dbt PRIMARY KEY (MSDB, MSTuyen),
    CONSTRAINT fk_msdb_dbt FOREIGN KEY (MSDB) REFERENCES THOITIET(MSDB),
	CONSTRAINT fk_mstuyen_dbt FOREIGN KEY (MSTuyen) REFERENCES TUYENDUONG(MSTuyen)
);
